name: 'private-npm-registry-setup'
services:
  verdaccio:
    image: verdaccio/verdaccio
    restart: unless-stopped
    ports:
      - 4873:4873
    volumes:
      - verdaccio-storage:/verdaccio/storage
volumes:
  verdaccio-storage:
